---
- name: Kali workstation deployment
  hosts: localhost
  connection: local
  vars_files:
    - group_vars/kali.yml
  roles:
    - apt
    - kali
    - xfce
    - rofi
    - docker
    - chrome 
    - autorecon
    - gowitness
