---
- name: apt update
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name: "*"
    state: latest
    cache_valid_time: 3600
    

- name: clean up
  become: true
  ansible.builtin.apt:
    autoclean: yes
    autoremove: yes
    clean: yes