---
- name: Upgrade all packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: "*"
    state: latest
    cache_valid_time: 3600

- name: Clean up
  become: true
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    clean: true
