- name: Add Chrome repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome

- name: Install Chrome
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg: google-chrome-stable
