---
- name: install dependencies
  become: yes
  ansible.builtin.apt:
    pkg:
      - curl
      - dnsrecon
      - enum4linux
      - feroxbuster
      - git
      - gobuster
      - impacket-scripts
      - nbtscan
      - nikto
      - nmap
      - onesixtyone
      - oscanner
      - python3
      - python3-pip
      - redis-tools
      - seclists
      - smbclient
      - smbmap
      - snmp
      - sslscan
      - sipvicious
      - tnscmd10g
      - whatweb
      - wkhtmltopdf
    state: present

- name: ensure python venv is installed
  become: yes
  ansible.builtin.apt:
    pkg: python3-venv
    state: present

- name: make autorecon dir
  ansible.builtin.file:
    path: /opt/autorecon
    state: directory
    mode: '0755'

- name: Install autorecon
  ansible.builtin.pip:
    name: git+https://github.com/Tib3rius/AutoRecon.git
    virtualenv: /opt/autorecon/venv

- name: add wrapper script to /usr/local/bin
  become: yes
  ansible.builtin.template:
    src: autorecon.j2
    dest: "/usr/local/bin/autorecon"

- name: ensure proper permissions
  become: yes
  ansible.builtin.file:
    path: /usr/local/bin/autorecon
    owner: root
    group: root
    mode: '0755'
