---
- name: Install packages
  become: true
  ansible.builtin.apt:
    pkg:
      - code-oss
      - amass
      - subfinder
      - assetfinder
      - ffuf
      - gobuster
      - dirsearch
      - golang-go

- name: Install python packages
  ansible.builtin.pip:
    extra_args: --user
    name:
      - ansible-lint

- name: Install gowitness
  ansible.builtin.command: "go install github.com/sensepost/gowitness@latest"
  changed_when: false

- name: Add go/bin and .local/bin to $PATH
  ansible.builtin.lineinfile:
    path: "{{ kali_home }}/.zshrc"
    line: export PATH="$PATH:{{ kali_home }}/go/bin"

- name: Add .local/bin to $PATH
  ansible.builtin.lineinfile:
    path: "{{ kali_home }}/.zshrc"
    line: export PATH="$PATH:{{ kali_home }}/.local/bin"

- name: Fix user-dirs.dirs
  ansible.builtin.template:
    src: user-dirs.dirs.j2
    dest: "{{ kali_home }}/.config/user-dirs.dirs"
    mode: '0600'

- name: Add user-dirs.conf
  ansible.builtin.template:
    src: user-dirs.conf.j2
    dest: "{{ kali_home }}/.config/user-dirs.conf"
    mode: '0600'

- name: Remove unnecessary directories
  ansible.builtin.file:
    state: absent
    path: "{{ kali_home }}/{{ item }}"
  with_items:
    - Desktop
    - Music
    - Pictures
    - Public
    - Templates
    - Videos

- name: Change ownership of /opt to kali
  become: yes
  ansible.builtin.file:
    state: directory
    path: /opt
    group: kali
    owner: kali

- name: Clone AutoRecon
  ansible.builtin.git:
    repo: 'https://github.com/Tib3rius/AutoRecon.git'
    dest: /opt/AutoRecon
    single_branch: yes
    version: main
    depth: 1
