---
- name: install packages
  become: true
  ansible.builtin.apt:
    pkg:
      - code-oss
      - amass
      - subfinder
      - assetfinder
      - ffuf
      - gobuster
      - dirsearch
      - golang-go

- name: install chrome
  become: true
  ansible.builtin.apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: install gowitness
  command: "go install github.com/sensepost/gowitness@latest"
  changed_when: no

- name: add go/bin and .local/bin to $PATH
  ansible.builtin.lineinfile:
    path: /home/kali/.zshrc
    line: export PATH="$PATH:/home/kali/go/bin"

- name: add .local/bin to $PATH
  ansible.builtin.lineinfile:
    path: /home/kali/.zshrc
    line: export PATH="$PATH:/home/kali/.local/bin"
